services:
  - type: web
    name: my-backend
    env: node

    # envVars:
    #   - key: NODE_ENV
    #     value: production
    #   - key: MONGO_URI
    #     value: ${MONGO_URI}  # Replace with your actual MongoDB URI or set in Render's dashboard
